version: '3'

services:
  app:
    build:
      context: ./app
    ports:
      - "5001:5000"
    depends_on:
      - database
    environment:
      - DATABASE_HOST=database
      - DATABASE_PORT=3307
      - DATABASE_USER=root
      - DATABASE_PASSWORD=example_password
      - DATABASE_NAME=mydb

  database:
    image: mariadb
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=example_password
      - MYSQL_DATABASE=mydb
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
